# 1. Numpy 생성
넘파이 실행 내용

In [2]:
import numpy as np

넘파이 외부모듈 실행

In [3]:
t_arr=np.array([1,4,5,8],float)
t_arr

array([1., 4., 5., 8.])

In [4]:
type(t_arr)

numpy.ndarray

In [5]:
type(t_arr[0])

numpy.float64

In [6]:
print(t_arr.dtype)

float64


In [7]:
print(t_arr.shape)

(4,)


In [8]:
mix=[[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(mix).shape

(3, 4)

In [10]:
t_3=[[[1,2,5,8],[1,2,5,8],[1,2,5,8]],
     [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
     [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
     [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(t_3).shape

(4, 3, 4)

In [11]:
t_3=[[[1,2,5,8],[1,2,5,8],[1,2,5,8]],
     [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
     [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
     [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(t_3).ndim

3

In [12]:
np.array(t_3).size

48

In [13]:
np.array([[1,2,3],[4,5,6]],dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
x=np.array([[1,2,5,8],[1,2,5,8]])
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [18]:
x=np.array([0,1,2,3,4,5,6,7])
x.reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [19]:
x.reshape(2,2,-1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [20]:
x=np.array([[1,2,3,4],[5,6,7,8]])
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
l=[[1,2,3,4],[5,6,7,8]]
l[0][0]

1

In [24]:
x=np.array(l)
x[0][0]
x[1,0]

5

In [27]:
x=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
x.shape

(2, 3, 5)

In [28]:
x[1,2,3]

14

In [29]:
x=np.array([[1,2,5,8],[1,2,5,8],[1,2,5,8],[1,2,5,8]])
x[:,2]

array([5, 5, 5, 5])

In [30]:
x[:2,:]

array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [31]:
x[:2,::2]

array([[1, 5],
       [1, 5]])

In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(1,101,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [37]:
np.ones(shape=(2,2,10))

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [38]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
np.full((2,2),10)

array([[10, 10],
       [10, 10]])

In [42]:
np.zeros((2,3))
x=np.arange(1,101,2)
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [44]:
np.ones_like(x)
np.zeros_like(x)
np.empty_like(x)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [45]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
np.eye(N=3,M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [47]:
np.eye(N=3,M=5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [49]:
mix=np.arange(9).reshape(3,3)
mix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
np.diag(mix,k=1)

array([1, 5])