# 2. Numpy 연산
연산을 통한 결과 

In [2]:
import numpy as np
t_a=np.arange(1,11)
t_a.sum()

55

In [3]:
t_a=np.arange(1,13).reshape(3,4)
t_a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
t_a.sum(axis=0)

array([15, 18, 21, 24])

In [5]:
t_a.sum(axis=1)

array([10, 26, 42])

In [7]:
t_a_2=np.array([t_a,t_a,t_a])
t_a_2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [8]:
t_a_2.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [9]:
t_a_2.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [10]:
t_a_2.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [67]:
v_a=np.array([1,2,3])
v_a_1=np.array([4,5,6])
np.vstack((v_a,v_a_1))

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
h_1=v_a.reshape(-1,1)
h_2=v_a_1.reshape(-1,1)
np.hstack((h_1,h_2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
x=np.arange(1,7).reshape(2,3)

In [20]:
x+x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [21]:
x-x

array([[0, 0, 0],
       [0, 0, 0]])

In [22]:
x*x

array([[ 1,  4,  9],
       [16, 25, 36]])

In [23]:
x/x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
x%x

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [25]:
x**x

array([[    1,     4,    27],
       [  256,  3125, 46656]], dtype=int32)

In [26]:
x==x

array([[ True,  True,  True],
       [ True,  True,  True]])

In [31]:
x=np.arange(1,7).reshape(2,3)
y=np.arange(1,7).reshape(3,2)
np.dot(x,y)
x.dot(y)

array([[22, 28],
       [49, 64]])

In [32]:
x+1

array([[2, 3, 4],
       [5, 6, 7]])

In [33]:
x=np.arange(1,13).reshape(4,3)

In [34]:
v=np.array([10,20,30])

In [35]:
x+v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [36]:
v2=np.array([1,2,3,4]).reshape(-1,1)

In [37]:
x+v2

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [38]:
v+v2

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34]])

In [39]:
x=np.arange(3,10)

In [40]:
x>5

array([False, False, False,  True,  True,  True,  True])

In [42]:
(x>5).all()

False

In [44]:
(x>5).any()

True

In [45]:
(x<1).all()

False

In [46]:
(x<1).any()

False

In [48]:
x=np.random.randint(1,100,100)
x

array([31, 92, 11, 62, 80, 49,  3, 47,  3, 68, 94, 90, 11, 27, 12, 11, 49,
       23, 82, 67, 87, 33, 90, 15, 80, 17, 87, 66, 78, 18, 98, 96, 12,  6,
       87, 49, 82, 51, 59, 61,  2, 97, 86, 51, 41, 88, 27, 39, 68, 37, 25,
       74, 68, 69, 59, 41, 24, 23,  1,  3, 25,  9, 18, 80, 15, 64,  8, 24,
       81,  4,  8, 15,  2, 80, 77, 10, 33, 94, 85, 86, 48, 73,  7, 51, 25,
       71, 20, 84, 90,  9, 12, 85, 15, 20, 63, 41, 73, 84, 68, 43])

In [69]:
x=np.array([1,2,3,4,5,1])
np.where(x==1,10,20)

array([10, 20, 20, 20, 20, 10])

In [51]:
d=np.array([1,5,4,3,7,2])
np.argsort(d)

array([0, 5, 3, 2, 1, 4], dtype=int64)

In [53]:
np.argmax(d)

4

In [54]:
np.argmin(d)

0

In [55]:
d[d>=5]

array([5, 7])

In [73]:
x=np.arange(1,11)

In [57]:
l=np.array([0,5,9])
x[l]

array([ 1,  6, 10])

In [77]:
x=x.reshape(2,-1)
i_1=np.array([0,1])
i_0=np.array([0,1])
x

x[i_0,i_1]

array([1, 7])

In [62]:
x=np.arange(1,11).reshape(2,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [65]:
x_l=np.array([x,x,x])
x_l

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [66]:
x_l[:,:,:4]

array([[[1, 2, 3, 4],
        [6, 7, 8, 9]],

       [[1, 2, 3, 4],
        [6, 7, 8, 9]],

       [[1, 2, 3, 4],
        [6, 7, 8, 9]]])